name: debian-nodejs-opencode

services:
  opencode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opencode
    hostname: opencode
    tty: true
    stdin_open: true
    working_dir: /workspace
    volumes:
      - ./workspaces/opencode:/workspace
      - opencode-home:/root

volumes:
  opencode-home:
